# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY . .
WORKDIR "/src/MBW.Nemlig2MQTT/"
RUN dotnet publish -c release -o /app -r linux-musl-x64 --self-contained false

# Final
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./MBW.Nemlig2MQTT"]